
import { PlaceHolderImages } from './placeholder-images';

export type Event = {
  id: string;
  name: string;
  category: 'Tech' | 'Cultural' | 'Sports' | 'Workshop' | 'Seminar';
  date: string;
  location: string;
  description: string;
  longDescription: string;
  organizer: {
    name: string;
    avatar: string;
  };
  image: string;
  price: number;
  college: string;
};

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const events: Event[] = [
  {
    id: '1',
    name: 'HackaFest 2024',
    category: 'Tech',
    date: 'October 26-27, 2024',
    location: 'SRMIST Main Campus',
    description: 'The biggest collegiate hackathon in the South. 36 hours of innovation.',
    longDescription: 'Join over 2000 students from around the globe for a weekend of coding, learning, and creating. HackaFest is a 36-hour hackathon where you can bring your wildest ideas to life. We provide the food, resources, and mentors; you bring the creativity. Whether you are a seasoned coder or just starting, there is a place for you here. Workshops on various technologies will be held throughout the event.',
    organizer: { name: 'Tech Club SRM', avatar: '/avatars/01.png' },
    image: findImage('tech-event-1'),
    price: 250,
    college: 'SRM Institute of Science and Technology',
  },
  {
    id: '2',
    name: 'Innovate & Inspire',
    category: 'Tech',
    date: 'November 12, 2024',
    location: 'Online',
    description: 'A series of talks from industry leaders in technology and AI.',
    longDescription: 'Innovate & Inspire is a virtual conference designed to connect you with the brightest minds in the tech industry. This year\'s theme is "The Future of AI". Our lineup of speakers includes CEOs, lead engineers, and researchers from top tech companies. The event will feature keynotes, panel discussions, and interactive Q&A sessions. All sessions will be recorded and available to attendees after the event.',
    organizer: { name: 'Shaastra, IITM', avatar: '/avatars/02.png' },
    image: findImage('tech-event-2'),
    price: 100,
    college: 'IIT Madras',
  },
  {
    id: '3',
    name: 'Milan - Cultural Fest',
    category: 'Cultural',
    date: 'September 15, 2024',
    location: 'Main Campus Quad',
    description: 'Celebrate diversity with music, dance, and a splash of color.',
    longDescription: 'Experience the vibrant Festival of Colors right on campus! This event is a celebration of diversity, unity, and the joy of life. Inspired by traditional festivals, we invite everyone to come together for an unforgettable day of music from live DJs, dance performances, delicious food from various cultures, and of course, the throwing of colored powders. It\'s a perfect way to de-stress and make new friends.',
    organizer: { name: 'Cultural Society, SRM', avatar: '/avatars/03.png' },
    image: findImage('cultural-event-1'),
    price: 150,
    college: 'SRM Institute of Science and Technology',
  },
  {
    id: '4',
    name: 'Global Food Fair',
    category: 'Cultural',
    date: 'November 5, 2024',
    location: 'Student Union, IITD',
    description: 'Taste the world! A culinary journey with dishes from over 20 countries.',
    longDescription: 'Embark on a culinary journey at our annual Global Food Fair. Student organizations representing over 20 countries will be preparing and selling traditional dishes. It\'s a delicious opportunity to explore different cultures through their food. From spicy curries to sweet pastries, there is something for every palate. The event will also feature cultural performances on the main stage.',
    organizer: { name: 'International Students Association', avatar: '/avatars/04.png' },
    image: findImage('cultural-event-2'),
    price: 200,
    college: 'IIT Delhi',
  },
  {
    id: '5',
    name: 'Spardha - Basketball Championship',
    category: 'Sports',
    date: 'December 1-5, 2024',
    location: 'University Arena, IITB',
    description: 'Witness the ultimate showdown as colleges battle for the trophy.',
    longDescription: 'The most anticipated sports event of the year is here! The Inter-College Basketball Championship brings together the best teams for a week of intense competition. Come and cheer for your college team as they battle it out on the court for glory and the coveted championship trophy. Expect thrilling matches, a roaring crowd, and an electrifying atmosphere.',
    organizer: { name: 'Athletics Department, IITB', avatar: '/avatars/05.png' },
    image: findImage('sports-event-1'),
    price: 50,
    college: 'IIT Bombay',
  },
  {
    id: '6',
    name: 'SRM Run',
    category: 'Sports',
    date: 'April 20, 2025',
    location: 'Campus Wide',
    description: 'Run for a cause! 5K and 10K runs open to all students and faculty.',
    longDescription: 'Lace up your running shoes for the Annual Campus Marathon! This year, we are running to support local charities. Choose between a 5K fun run or a more challenging 10K route that takes you through the beautiful sights of our campus. It\'s a great way to stay fit, challenge yourself, and contribute to a good cause. All participants will receive a finisher\'s medal and a t-shirt.',
    organizer: { name: 'Sports Council, SRM', avatar: '/avatars/01.png' },
    image: findImage('sports-event-2'),
    price: 300,
    college: 'SRM Institute of Science and Technology',
  },
  {
    id: '7',
    name: 'RoboFest',
    category: 'Tech',
    date: 'October 1, 2024',
    location: 'Tech Park, SRM',
    description: 'Build and battle robots in this exciting competition.',
    longDescription: 'RoboFest is a thrilling two-day event where participants design, build, and program their own robots to compete in various challenges. From sumo-bots to line-followers, there are categories for all skill levels. We also have workshops on robotics and programming for beginners.',
    organizer: { name: 'Next Tech Lab', avatar: '/avatars/01.png' },
    image: findImage('tech-event-3'),
    price: 400,
    college: 'SRM Institute of Science and Technology',
  },
  {
    id: '8',
    name: 'Elysian',
    category: 'Cultural',
    date: 'October 5, 2024',
    location: 'Amphitheatre, SRM',
    description: 'A night of music, drama, and dance performances.',
    longDescription: 'Elysian is our annual cultural extravaganza, showcasing the incredible talent of our students. The evening will be filled with captivating performances, including live bands, theatrical plays, and breathtaking dance routines. Come and be mesmerized!',
    organizer: { name: 'Dance Club SRM', avatar: '/avatars/01.png' },
    image: findImage('cultural-event-3'),
    price: 200,
    college: 'SRM Institute of Science and Technology',
  },
  {
    id: '9',
    name: 'Nariyukti Hackathon',
    category: 'Tech',
    date: 'October 10, 2024',
    location: 'Innovation Center, SRM',
    description: 'A hackathon focused on solutions for women empowerment.',
    longDescription: 'Nariyukti Hackathon is a special event aimed at creating technology-driven solutions to address challenges faced by women. We invite coders, designers, and thinkers to collaborate and build something meaningful. Mentors from the industry will be present to guide the teams.',
    organizer: { name: 'SRM WE-ASC', avatar: '/avatars/01.png' },
    image: findImage('tech-event-4'),
    price: 0,
    college: 'SRM Institute of Science and Technology',
  },
  {
    id: '10',
    name: 'ACM Summit',
    category: 'Seminar',
    date: 'November 1, 2024',
    location: 'Conference Hall, SRM',
    description: 'A summit with leading researchers in computer science.',
    longDescription: 'The ACM Summit brings together renowned researchers and professionals to discuss the latest advancements in computer science. The summit will feature keynote speeches, paper presentations, and panel discussions on topics like AI, blockchain, and quantum computing.',
    organizer: { name: 'SRM ACM Student Chapter', avatar: '/avatars/02.png' },
    image: findImage('seminar-event-1'),
    price: 500,
    college: 'SRM Institute of Science and Technology',
  },
  {
    id: '11',
    name: 'Idea Forge',
    category: 'Workshop',
    date: 'November 8, 2024',
    location: 'Ideation Lab, SRM',
    description: 'A workshop on brainstorming and validating startup ideas.',
    longDescription: 'Have a startup idea? Idea Forge is the perfect place to shape it. This interactive workshop will guide you through the process of brainstorming, market research, and validating your business idea. Learn from successful entrepreneurs and get feedback on your concept.',
    organizer: { name: 'SRM ACM Student Chapter', avatar: '/avatars/02.png' },
    image: findImage('workshop-event-1'),
    price: 100,
    college: 'SRM Institute of Science and Technology',
  },
  {
    id: '12',
    name: 'Pair Programming Contest',
    category: 'Tech',
    date: 'November 15, 2024',
    location: 'Programming Lab, SRM',
    description: 'Team up and solve challenging coding problems.',
    longDescription: 'Test your coding and collaboration skills in our Pair Programming Contest. In teams of two, you will race against time to solve a series of algorithmic challenges. Prizes for the top three teams. Food and drinks will be provided.',
    organizer: { name: 'SRM ACM Student Chapter', avatar: '/avatars/02.png' },
    image: findImage('tech-event-5'),
    price: 50,
    college: 'SRM Institute of Science and Technology',
  },
  {
    id: '13',
    name: 'Campus Quest',
    category: 'Cultural',
    date: 'December 1, 2024',
    location: 'Campus-wide, Loyola',
    description: 'A treasure hunt across the campus with exciting clues.',
    longDescription: 'Embark on an adventure with Campus Quest! Solve riddles, find hidden clues, and race across the campus in this exciting treasure hunt. Form a team with your friends and compete for the grand prize. It is a fun way to explore the campus and test your problem-solving skills.',
    organizer: { name: 'Literary Society', avatar: '/avatars/03.png' },
    image: findImage('cultural-event-4'),
    price: 100,
    college: 'Loyola College',
  },
  {
    id: '14',
    name: 'CAD Workshop',
    category: 'Workshop',
    date: 'December 5, 2024',
    location: 'Design Studio, Loyola',
    description: 'Learn the basics of Computer-Aided Design with Fusion 360.',
    longDescription: 'This hands-on workshop will introduce you to the fundamentals of Computer-Aided Design (CAD) using Fusion 360. You will learn to create 2D sketches and 3D models. This workshop is perfect for beginners in engineering and design.',
    organizer: { name: 'Mech Society', avatar: '/avatars/03.png' },
    image: findImage('workshop-event-2'),
    price: 150,
    college: 'Loyola College',
  },
  {
    id: '15',
    name: 'Web Dev Sprint',
    category: 'Tech',
    date: 'December 10, 2024',
    location: 'Online',
    description: 'Build a complete web application in a weekend.',
    longDescription: 'Join our Web Dev Sprint and learn how to build a full-stack web application from scratch. This intensive workshop will cover everything from frontend frameworks like React to backend development with Node.js. No prior experience is required.',
    organizer: { name: 'Dev Club IITM', avatar: '/avatars/03.png' },
    image: findImage('tech-event-6'),
    price: 250,
    college: 'IIT Madras',
  },
  {
    id: '16',
    name: 'Solidworks Bootcamp',
    category: 'Workshop',
    date: 'January 10, 2025',
    location: 'Mechanical Lab, IITM',
    description: 'An intensive bootcamp on advanced Solidworks features.',
    longDescription: 'Take your Solidworks skills to the next level with our advanced bootcamp. This session will cover complex assemblies, simulations, and surface modeling. This is for students with a basic understanding of Solidworks.',
    organizer: { name: 'Robotics Club IITM', avatar: '/avatars/04.png' },
    image: findImage('workshop-event-3'),
    price: 300,
    college: 'IIT Madras',
  },
  {
    id: '17',
    name: 'Altium Workshop',
    category: 'Workshop',
    date: 'January 15, 2025',
    location: 'Electronics Lab, IITM',
    description: 'Learn PCB design with Altium Designer.',
    longDescription: 'This workshop provides a comprehensive introduction to PCB design using Altium Designer, the industry-standard software. You will learn to create schematics, design PCB layouts, and generate manufacturing files. Perfect for electronics enthusiasts.',
    organizer: { name: 'Electronics Club, IITM', avatar: '/avatars/04.png' },
    image: findImage('workshop-event-4'),
    price: 300,
    college: 'IIT Madras',
  },
  {
    id: '18',
    name: 'Intro to Robotics',
    category: 'Seminar',
    date: 'January 20, 2025',
    location: 'Auditorium, IITD',
    description: 'A seminar on the fundamentals of robotics and automation.',
    longDescription: 'This seminar offers a broad overview of the field of robotics, covering topics like kinematics, sensors, actuators, and control systems. Learn about the latest trends and career opportunities in robotics and automation from an industry expert.',
    organizer: { name: 'Robotics Club, IITD', avatar: '/avatars/04.png' },
    image: findImage('seminar-event-2'),
    price: 50,
    college: 'IIT Delhi',
  },
  {
    id: '19',
    name: 'E-Summit Bombay',
    category: 'Seminar',
    date: 'February 1, 2025',
    location: 'Convention Center, Mumbai',
    description: 'The largest entrepreneurship summit in the region.',
    longDescription: 'E-Summit is a two-day extravaganza of entrepreneurship, featuring talks by famous founders, pitch competitions, and networking sessions. Whether you have a startup or just an idea, this is the place to be for inspiration and connections.',
    organizer: { name: 'E-Cell IITB', avatar: '/avatars/05.png' },
    image: findImage('seminar-event-3'),
    price: 500,
    college: 'IIT Bombay',
  },
  {
    id: '20',
    name: 'Pixelothon Delhi',
    category: 'Tech',
    date: 'February 5, 2025',
    location: 'Design Hub, IITD',
    description: 'A UI/UX designathon to create beautiful and user-friendly interfaces.',
    longDescription: 'Pixelothon is a 24-hour designathon where you will work in teams to design a user interface for a given problem statement. Sharpen your UI/UX skills, learn from experienced mentors, and win exciting prizes. No coding required.',
    organizer: { name: 'Design Club, IITD', avatar: '/avatars/05.png' },
    image: findImage('tech-event-7'),
    price: 100,
    college: 'IIT Delhi',
  },
  {
    id: '21',
    name: 'E-Gnite Bombay',
    category: 'Cultural',
    date: 'February 10, 2025',
    location: 'Open Air Theatre, IITB',
    description: 'An evening of celebration with startup success stories and music.',
    longDescription: 'E-Gnite is a celebration of the entrepreneurial spirit. Join us for an inspiring evening where successful entrepreneurs share their journeys, followed by live music performances and dinner. It is a great opportunity to network in a relaxed setting.',
    organizer: { name: 'E-Cell IITB', avatar: '/avatars/05.png' },
    image: findImage('cultural-event-5'),
    price: 250,
    college: 'IIT Bombay',
  },
  {
    id: '22',
    name: 'Rendezvous',
    category: 'Cultural',
    date: 'Oct 15-18, 2024',
    location: 'IIT Delhi Campus',
    description: 'North India\'s largest cultural festival.',
    longDescription: 'Rendezvous is the annual Cultural Festival of the Indian Institute of Technology (IIT), Delhi. It is a four-day-long event held in October every year. It draws a footfall of over 50,000 from more than 500 colleges across the country.',
    organizer: { name: 'Student Board, IITD', avatar: '/avatars/01.png' },
    image: findImage('cultural-event-1'),
    price: 800,
    college: 'IIT Delhi',
  },
  {
    id: '23',
    name: 'Tryst',
    category: 'Tech',
    date: 'Feb 20-23, 2025',
    location: 'IIT Delhi Campus',
    description: 'The annual technical festival of IIT Delhi.',
    longDescription: 'Tryst is the annual technical festival of the Indian Institute of Technology Delhi, held in February and March. It is a four-day-long festival, which is one of the largest of its kind in India.',
    organizer: { name: 'Tech Council, IITD', avatar: '/avatars/02.png' },
    image: findImage('tech-event-1'),
    price: 600,
    college: 'IIT Delhi',
  },
  {
    id: '24',
    name: 'Mood Indigo',
    category: 'Cultural',
    date: 'Dec 20-23, 2024',
    location: 'IIT Bombay Campus',
    description: 'Asia\'s largest college cultural festival.',
    longDescription: 'Mood Indigo, affectionately known as MoodI, is the annual cultural festival of the Indian Institute of Technology Bombay. It is an event held towards the end of December every year. The 2019 edition of Mood Indigo witnessed a footfall of 1,46,000.',
    organizer: { name: 'Student Body, IITB', avatar: '/avatars/03.png' },
    image: findImage('cultural-event-2'),
    price: 1000,
    college: 'IIT Bombay',
  },
  {
    id: '25',
    name: 'Techfest',
    category: 'Tech',
    date: 'Jan 3-5, 2025',
    location: 'IIT Bombay Campus',
    description: 'Asia\'s largest science and technology festival.',
    longDescription: 'Techfest is the annual science and technology festival of Indian Institute of Technology Bombay. It was started in 1998, and since then it has become one of the most prominent festivals of its kind in Asia.',
    organizer: { name: 'Techfest Team, IITB', avatar: '/avatars/04.png' },
    image: findImage('tech-event-2'),
    price: 750,
    college: 'IIT Bombay',
  },
  {
    id: '26',
    name: 'Antaragni',
    category: 'Cultural',
    date: 'Oct 24-27, 2024',
    location: 'NSUT, Delhi',
    description: 'A cultural festival of music, arts, and literature.',
    longDescription: 'Antaragni is the annual cultural festival of the Netaji Subhas University of Technology. It is a four-day-long event held in October every year.',
    organizer: { name: 'Cultural Committee, NSUT', avatar: '/avatars/05.png' },
    image: findImage('cultural-event-3'),
    price: 500,
    college: 'Netaji Subhas University of Technology',
  },
  {
    id: '27',
    name: 'Moksha',
    category: 'Cultural',
    date: 'Mar 12-15, 2025',
    location: 'NSUT, Delhi',
    description: 'Annual cultural festival of NSUT.',
    longDescription: 'Moksha is the annual cultural festival of the Netaji Subhas University of Technology. The festival is a three-day-long event held in March every year.',
    organizer: { name: 'Student Council, NSUT', avatar: '/avatars/01.png' },
    image: findImage('cultural-event-4'),
    price: 450,
    college: 'Netaji Subhas University of Technology',
  },
  {
    id: '28',
    name: 'Oasis',
    category: 'Cultural',
    date: 'Nov 1-4, 2024',
    location: 'BITS Pilani, Hyderabad Campus',
    description: 'The annual cultural festival of BITS Pilani, Hyderabad Campus.',
    longDescription: 'Oasis is the annual cultural festival of the Birla Institute of Technology and Science, Pilani – Hyderabad Campus. It is a four-day festival organized in the first semester of the academic year.',
    organizer: { name: 'BITS Hyderabad Students', avatar: '/avatars/02.png' },
    image: findImage('cultural-event-5'),
    price: 900,
    college: 'BITS Pilani, Hyderabad Campus',
  },
  {
    id: '29',
    name: 'ATMOS',
    category: 'Tech',
    date: 'Oct 26-28, 2024',
    location: 'BITS Pilani, Hyderabad Campus',
    description: 'The annual techno-management festival of BITS Pilani, Hyderabad Campus.',
    longDescription: 'ATMOS is the annual techno-management festival of BITS Pilani, Hyderabad Campus. It is known for a variety of events, including workshops, competitions, paper presentations, and guest lectures.',
    organizer: { name: 'Tech Association, BITS Hyderabad', avatar: '/avatars/03.png' },
    image: findImage('tech-event-3'),
    price: 550,
    college: 'BITS Pilani, Hyderabad Campus',
  },
  {
    id: '30',
    name: 'Pravega',
    category: 'Tech',
    date: 'Jan 17-19, 2025',
    location: 'IISC Bangalore',
    description: 'The annual science, technology and cultural festival of IISc Bangalore.',
    longDescription: 'Pravega is the annual science, technology and cultural festival of the Indian Institute of Science, Bangalore. The festival is held in January and attracts students from all over the country.',
    organizer: { name: 'IISC Student Council', avatar: '/avatars/04.png' },
    image: findImage('tech-event-4'),
    price: 700,
    college: 'Indian Institute of Science',
  },
  {
    id: '31',
    name: 'Atmatrisha',
    category: 'Cultural',
    date: 'Apr 4-6, 2025',
    location: 'PES University, Bangalore',
    description: 'The annual cultural fest of PES University.',
    longDescription: 'Aatmatrisha is the annual cultural fest of PES University, which is held in April. The festival hosts a variety of events like dance, music, drama, and fashion shows.',
    organizer: { name: 'PES Events Team', avatar: '/avatars/05.png' },
    image: findImage('cultural-event-1'),
    price: 400,
    college: 'PES University',
  },
  {
    id: '32',
    name: 'Felicity',
    category: 'Tech',
    date: 'Jan 24-26, 2025',
    location: 'IIIT Hyderabad',
    description: 'The annual technical and cultural festival of IIIT Hyderabad.',
    longDescription: 'Felicity is the annual technical and cultural festival of the International Institute of Information Technology, Hyderabad. The festival includes a variety of technical and cultural events.',
    organizer: { name: 'IIITH Student Body', avatar: '/avatars/01.png' },
    image: findImage('tech-event-5'),
    price: 650,
    college: 'IIIT Hyderabad',
  },
  {
    id: '33',
    name: 'Zeitgeist',
    category: 'Cultural',
    date: 'Oct 11-13, 2024',
    location: 'IIT Ropar',
    description: 'The annual cultural festival of IIT Ropar.',
    longDescription: 'Zeitgeist is the annual cultural festival of the Indian Institute of Technology, Ropar. It is a three-day festival held in October.',
    organizer: { name: 'Cultural Board, IIT Ropar', avatar: '/avatars/02.png' },
    image: findImage('cultural-event-2'),
    price: 500,
    college: 'IIT Ropar',
  },
  {
    id: '34',
    name: 'Saturnalia',
    category: 'Cultural',
    date: 'Nov 22-24, 2024',
    location: 'Thapar Institute, Patiala',
    description: 'The annual cultural fest of Thapar Institute of Engineering and Technology.',
    longDescription: 'Saturnalia is the annual cultural fest of Thapar Institute of Engineering and Technology, Patiala. It is one of the biggest fests in North India.',
    organizer: { name: 'Student Organizers, Thapar', avatar: '/avatars/03.png' },
    image: findImage('cultural-event-3'),
    price: 450,
    college: 'Thapar Institute of Engineering and Technology',
  },
  {
    id: '35',
    name: 'Colosseum',
    category: 'Sports',
    date: 'Feb 14-16, 2025',
    location: 'SPIT, Mumbai',
    description: 'The annual sports festival of Sardar Patel Institute of Technology.',
    longDescription: 'Colosseum is the annual sports festival of Sardar Patel Institute of Technology, Mumbai. The festival includes competitions in various sports like cricket, football, and basketball.',
    organizer: { name: 'Sports Committee, SPIT', avatar: '/avatars/04.png' },
    image: findImage('sports-event-1'),
    price: 200,
    college: 'Sardar Patel Institute of Technology',
  },
  {
    id: '36',
    name: 'Udaan',
    category: 'Cultural',
    date: 'Mar 7-9, 2025',
    location: 'SPIT, Mumbai',
    description: 'The annual cultural festival of SPIT, Mumbai.',
    longDescription: 'Udaan is the annual cultural festival of Sardar Patel Institute of Technology, Mumbai. The three-day festival is a blend of music, dance, and drama.',
    organizer: { name: 'Cultural Team, SPIT', avatar: '/avatars/05.png' },
    image: findImage('cultural-event-4'),
    price: 350,
    college: 'Sardar Patel Institute of Technology',
  },
  {
    id: '37',
    name: 'Threads',
    category: 'Tech',
    date: 'Mar 21-23, 2025',
    location: 'IIIT Hyderabad',
    description: 'The annual technical symposium of IIIT Hyderabad.',
    longDescription: 'Threads is the annual technical symposium organized by the students of IIIT Hyderabad. It includes workshops, coding competitions, and guest lectures from eminent personalities in the tech world.',
    organizer: { name: 'Tech Society, IIITH', avatar: '/avatars/01.png' },
    image: findImage('tech-event-6'),
    price: 300,
    college: 'IIIT Hyderabad',
  },
  {
    id: '38',
    name: 'Advitiya',
    category: 'Tech',
    date: 'Feb 28 - Mar 2, 2025',
    location: 'IIT Ropar',
    description: 'The annual technical festival of IIT Ropar.',
    longDescription: 'Advitiya is the annual technical festival of the Indian Institute of Technology, Ropar. The festival hosts a series of technical competitions, workshops, and guest lectures.',
    organizer: { name: 'Tech Board, IIT Ropar', avatar: '/avatars/02.png' },
    image: findImage('tech-event-7'),
    price: 400,
    college: 'IIT Ropar',
  },
  {
    id: '39',
    name: 'Aranya',
    category: 'Cultural',
    date: 'Jan 31 - Feb 2, 2025',
    location: 'Thapar Institute, Patiala',
    description: 'A 3-day cultural fest with a focus on environmental awareness.',
    longDescription: 'Aranya is a unique cultural festival at Thapar Institute that combines cultural events with a strong message of environmental conservation. It features workshops on sustainability, eco-friendly art installations, and performances.',
    organizer: { name: 'Green Club, Thapar', avatar: '/avatars/03.png' },
    image: findImage('cultural-event-5'),
    price: 200,
    college: 'Thapar Institute of Engineering and Technology',
  },
  {
    id: '40',
    name: 'Praxis',
    category: 'Workshop',
    date: 'Nov 29-30, 2024',
    location: 'IISC Bangalore',
    description: 'A hands-on workshop on machine learning applications.',
    longDescription: 'Praxis is a two-day intensive workshop on machine learning. Participants will get hands-on experience in building and deploying machine learning models. The workshop is suitable for students with a basic knowledge of programming.',
    organizer: { name: 'AI Club, IISC', avatar: '/avatars/04.png' },
    image: findImage('workshop-event-1'),
    price: 800,
    college: 'Indian Institute of Science',
  },
   {
    id: '41',
    name: 'PyData Conference',
    category: 'Seminar',
    date: 'Dec 6-7, 2024',
    location: 'IIIT Hyderabad',
    description: 'A conference for the developers and users of data analysis tools.',
    longDescription: 'PyData brings together users and developers of data analysis tools to share ideas and learn from each other. The conference features talks on a wide range of topics, including data science, machine learning, and big data technologies.',
    organizer: { name: 'PyData Hyderabad Chapter', avatar: '/avatars/05.png' },
    image: findImage('seminar-event-2'),
    price: 1200,
    college: 'IIIT Hyderabad',
  },
  {
    id: '42',
    name: 'Samgacchadhwam',
    category: 'Cultural',
    date: 'Feb 21-23, 2025',
    location: 'IISC Bangalore',
    description: 'A cultural festival celebrating the confluence of science and arts.',
    longDescription: 'Samgacchadhwam, which means "Let us move together", is a festival that celebrates the synergy between science and the arts. The event features art installations inspired by scientific concepts, dance performances depicting scientific phenomena, and more.',
    organizer: { name: 'Arts Forum, IISC', avatar: '/avatars/01.png' },
    image: findImage('cultural-event-1'),
    price: 300,
    college: 'Indian Institute of Science',
  },
  {
    id: '43',
    name: 'Aaruush',
    category: 'Tech',
    date: 'Sep 19-22, 2024',
    location: 'SRM Institute of Science and Technology',
    description: 'A national level techno-management fest.',
    longDescription: 'Aaruush is a National Level Techno-Management fest organized by the students of SRM Institute of Science and Technology. It has been a platform for innovation and creativity since its inception in 2007.',
    organizer: { name: 'Team Aaruush', avatar: '/avatars/02.png' },
    image: findImage('tech-event-2'),
    price: 500,
    college: 'SRM Institute of Science and Technology',
  },
  {
    id: '44',
    name: 'Pinnacle',
    category: 'Sports',
    date: 'Mar 14-16, 2025',
    location: 'PES University, Bangalore',
    description: 'The flagship sports festival of PES University.',
    longDescription: 'Pinnacle is the flagship sports festival of PES University, Bangalore. The three-day festival sees participation from colleges across the country in a wide range of sports.',
    organizer: { name: 'Sports Council, PES', avatar: '/avatars/03.png' },
    image: findImage('sports-event-2'),
    price: 250,
    college: 'PES University',
  }
];

export const eventCategories = ['Tech', 'Cultural', 'Sports', 'Workshop', 'Seminar'];

    
